version: "2"
services:
    www:
        build: .
        ports:
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - mysql
        networks:
            - default
    mysql:
        image: mariadb:latest
        container_name: test-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: docker
            DB_DATABASE: mazhr
            DB_USERNAME: root
            DB_PASSWORD: docker
        volumes:
            - ./mysql:/var/lib/mysql
networks:
    wv-net:
        driver: "bridge"
volumes:
    wvsqldata:
        driver: "local"
